site_name: DugonSNAP
theme:
  name: material
markdown_extensions:
  - pymdownx.highlight:
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
nav:
  - Introduction: introduction/index.md